// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MockKafkaProducer is an autogenerated mock type for the Producer type
type MockKafkaProducer struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *MockKafkaProducer) Close() {
	_m.Called()
}

// Produce provides a mock function with given fields: topic, key, value
func (_m *MockKafkaProducer) Produce(topic string, key string, value []byte) error {
	ret := _m.Called(topic, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Produce")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, []byte) error); ok {
		r0 = rf(topic, key, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockKafkaProducer creates a new instance of MockKafkaProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockKafkaProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockKafkaProducer {
	mock := &MockKafkaProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
