app:
  address: "0.0.0.0:8936"
api:
  threat: "http://api.os.ti.visc.com/threat-service"
  opv1: "http://operation-api.os.ti.visc.com/api/v1"
adapter:
  elastic:
    enduser:
      version: 7
      scheme: "http"
      address: "localhost:9211"
      auth:
        enable: false
        username: ""
        password: ""
  mongo:
    account:
      address: "mg-admin:vtios@localhost:27011/?directConnection=true"
      auth:
        enable: false
        username: "mg-admin"
        password: "vti-platform"
        auth_db: "admin"
    settings:
      address: "localhost:27017"
      auth:
        enable: false
        username: ""
        password: ""
        auth_db: ""
  rabbit:
    crawler:
      secure: false
      address: "localhost:5172"
      username: "ti-crawler"
      password: "vtios"
  kafka:
    producer:
      brokers: "localhost:9092"
      async: true
    topic:
      ti_asset_events: "isac-ti_asset_events"
  redis:
    cache:
      address: "localhost:6379"
      password: "vtios"
      db: 11
mail:
  base_url: "http://desktop.ti.visc.com"
  portal_public_url: "https://your-domain.com"
  base_page: "https://your-domain.com"
  phone_contact: "0971 360 360"
  sale_contact: "vcs.care@viettel.com.vn"
  sale_contact_1: "vcs.care@viettel.com.vn"
  url_login: "https://your-domain.com/login"
  user_guide:
    en: "https://your-domain.com/guide-en"
    vi: "https://your-domain.com/guide-vi"
  link_package: "https://your-domain.com/package"
  template_path: "./templates/email"
  smtp_host: ""
  smtp_port: "1025"
  from_email: "chiennt11@viettel.com.vn"
  from_name: "Test System"
  smtp_username: ""
  smtp_password: ""
  api: "http://mail.ti.visc.com/send"
  debug: true