app:
  address: "localhost:8936"
  secret: "826c0cbb6f0898cf6a2eceaf6d954889"
  sync_asset_mapping_index: false
api:
  threat: "http://api.staging.ti.visc.com/threat-service"
  opv1: "http://operation-api.os.ti.visc.com/api/v1"
adapter:
  elastic:
    enduser:
      version: 7
      scheme: "http"
      address: "localhost:9220"
      auth:
        enable: false
        username: ""
        password: ""
  mongo:
    account:
      address: "mg-admin:vtios@localhost:27011/?directConnection=true"
      auth:
        enable: false
        username: ""
        password: ""
        auth_db: ""
    settings:
      address: "mg-admin:vtios@localhost:27011/?directConnection=true"
      auth:
        enable: false
        username: ""
        password: ""
        auth_db: ""
  rabbit:
    crawler:
      secure: false
      address: "localhost:5172"
      username: "ti-crawler"
      password: "vtios"
  kafka:
    brokers: "localhost:9092"
    async: true
  redis:
    cache:
      address: "localhost:6379"
      password: "vtios"
      db: 11
mail:
  base_url: "https://platform.os.ti.visc.com"
  portal_public_url: "https://platform.os.ti.visc.com"
  base_page: "https://platform.os.ti.visc.com"
  phone_contact: "(+84) 326 360 360"
  sale_contact: "cyberthreat@viettel.com.vn"
  sale_contact_1: "cskh_anm@viettel.com.vn"
  url_login: "https://platform.os.ti.visc.com/#/login"
  user_guide:
    en: "https://docv2-en.cyberintel.io/#/guide"
    vi: "https://docv2.cyberintel.io/#/guide"
  link_package: "https://platform.os.ti.visc.com"
  template_path: "./templates/email"
  mail_api: "http://mail.ti.visc.com/send"
